# Generated by Django 5.2 on 2025-05-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(help_text='A little bio for the faction, who are they, what drives them etc.')),
            ],
        ),
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('settlement_score', models.IntegerField(default=20)),
                ('last_foraged', models.DateTimeField(verbose_name='last foraging')),
            ],
        ),
        migrations.CreateModel(
            name='Strongholdtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('loot_multiplier', models.IntegerField(default=0)),
                ('starting_infantry', models.IntegerField(default=0)),
                ('starting_cavalry', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Unittype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('road_speed', models.IntegerField(default=0)),
                ('offroad_speed', models.IntegerField(default=0)),
                ('scout_distance', models.IntegerField(default=0)),
                ('supplies_per_day', models.IntegerField(default=0)),
                ('carry_weight', models.IntegerField(default=0)),
                ('units_per_mile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataphract.faction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataphract.hex')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('commander', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.commander')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.faction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataphract.hex')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField()),
                ('date_start', models.DateTimeField(verbose_name='start of order')),
                ('date_end', models.DateTimeField(verbose_name='end of order')),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataphract.commander')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('last_recruitement', models.DateTimeField(verbose_name='last recruitment')),
                ('faction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.faction')),
            ],
        ),
        migrations.CreateModel(
            name='Strongholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('gate', models.BooleanField(default=True)),
                ('sieged', models.BooleanField(default=False)),
                ('loot', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.faction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataphract.hex')),
            ],
        ),
        migrations.CreateModel(
            name='Detachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('units', models.IntegerField(default=0)),
                ('non_combantants', models.IntegerField(default=0)),
                ('wagons', models.IntegerField(default=0)),
                ('supplies', models.IntegerField(default=0)),
                ('loot', models.IntegerField(default=0)),
                ('personal_loot', models.IntegerField(default=0)),
                ('morale', models.IntegerField(default=9)),
                ('unittype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataphract.unittype')),
            ],
        ),
    ]
