# Generated by Django 5.2 on 2025-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hex',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='hex',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hex',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
