# Generated by Django 5.2 on 2025-05-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0002_remove_hex_choice_text_hex_x_hex_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='hex',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.region'),
        ),
        migrations.AddField(
            model_name='strongholds',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.region'),
        ),
        migrations.AlterField(
            model_name='strongholds',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.hex'),
        ),
    ]
