# Generated by Django 5.2 on 2025-05-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0003_hex_region_strongholds_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discord_id', models.IntegerField(default=0)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='commander',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='hex',
            name='river',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hex',
            name='road',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='unique_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.IntegerField(choices=[(1, 'Move'), (2, 'Rest'), (3, 'Build'), (4, 'Unique')], default=1),
        ),
        migrations.AddField(
            model_name='commander',
            name='player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.player'),
        ),
    ]
