# Generated by Django 5.2 on 2025-05-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0004_player_commander_age_hex_river_hex_road_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detachment',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.army'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.commander'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hex',
            name='settlement_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.IntegerField(choices=[(1, 'Move'), (2, 'Rest'), (3, 'Build'), (4, 'Recruit'), (5, 'Forage'), (6, 'Siege'), (7, 'Unique')], default=1),
        ),
        migrations.CreateModel(
            name='ObservedHex',
            fields=[
                ('hex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cataphract.hex')),
                ('Date_Observed', models.DateTimeField(verbose_name='last observed')),
                ('Commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.commander')),
            ],
            bases=('cataphract.hex',),
        ),
    ]
