# Generated by Django 5.2 on 2025-05-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0005_detachment_army_detachment_commander_order_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detachment',
            name='commander',
        ),
    ]
