# Generated by Django 5.2 on 2025-05-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0006_remove_detachment_commander'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='forced_march_speed',
            field=models.IntegerField(default=0),
        ),
    ]
