# Generated by Django 5.2 on 2025-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0007_unittype_forced_march_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
