# Generated by Django 5.2 on 2025-05-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0008_alter_player_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_hex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_hex', to='cataphract.hex'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_hex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='starting_hex', to='cataphract.hex'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end of order'),
        ),
    ]
