# Generated by Django 5.2 on 2025-05-26 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0009_order_end_hex_order_start_hex_alter_order_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='base_unit_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.unittype'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='default_non_combatant',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='unittype',
            name='recruitement_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='unittype',
            name='recruitement_rate_good_country',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='unittype',
            name='unique_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unittype',
            name='unique_type_faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.faction'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(default='Taylor', max_length=200),
        ),
    ]
