# Generated by Django 5.2 on 2026-01-14 14:22

import datetime
import faker.providers.address
import faker.providers.company
import faker.providers.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0013_alter_army_location_alter_commander_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_guild', models.IntegerField(default=0)),
                ('discord_channel_id', models.IntegerField(default=0)),
                ('discord_channel_name', models.CharField(default='cataphracts')),
                ('world_name', models.CharField(default=faker.providers.person.Provider.last_name)),
                ('world_width', models.IntegerField(default=0)),
                ('world_height', models.IntegerField(default=0)),
                ('last_tick', models.DateTimeField(default=datetime.datetime.now, verbose_name='last ingame tick')),
                ('tick_speed', models.IntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='army',
            name='harried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commander',
            name='map_sprite',
            field=models.ImageField(default='bandit.png', upload_to='units/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commander',
            name='portrait',
            field=models.ImageField(default='bandit.webp', upload_to='portraits/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hex',
            name='foraged_amount_season',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hex',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='week_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commander',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='bio',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(default=faker.providers.company.Provider.company, max_length=200),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.IntegerField(choices=[(1, 'Move'), (2, 'Rest'), (3, 'Build'), (4, 'Recruit'), (5, 'Forage'), (6, 'Siege'), (7, 'Harrying - killing soldiers'), (8, 'Harrying - torching supplies'), (9, 'Harrying - stealing loot'), (10, 'Operations')], default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='strongholds',
            name='name',
            field=models.CharField(default=faker.providers.address.Provider.city, max_length=200),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
    ]
