# Generated by Django 5.2 on 2026-01-19 17:36

import django.db.models.deletion
import faker.providers.address
import faker.providers.company
import faker.providers.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0014_world_army_harried_commander_map_sprite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_speed_bonus', models.IntegerField(default=0)),
                ('forced_march_speed_bonus', models.IntegerField(default=0)),
                ('offroad_speed_bonus', models.IntegerField(default=0)),
                ('scout_distance_bonus', models.IntegerField(default=0)),
                ('supplies_per_day_bonus', models.IntegerField(default=0)),
                ('harrier_bonus_bonus', models.IntegerField(default=0)),
                ('carry_weight_bonus', models.IntegerField(default=0)),
                ('carry_weight_modifier', models.FloatField(default=0.0)),
                ('units_per_mile_bonus', models.IntegerField(default=0)),
                ('default_non_combatant_modifier', models.FloatField(default=0.0)),
                ('pick_up_non_combatant_modifier', models.FloatField(default=0.0)),
                ('recruitement_rate_bonus', models.FloatField(default=0)),
                ('resting_morale_bonus', models.IntegerField(default=0)),
                ('besiege_bonus', models.IntegerField(default=0)),
                ('defend_stronghold_bonus', models.IntegerField(default=0)),
                ('duelist_bonus', models.IntegerField(default=0.0)),
                ('casualties_modifier', models.FloatField(default=0.0)),
                ('capturechance_bonus', models.IntegerField(default=0)),
                ('pillage_chance_bonus', models.IntegerField(default=0)),
                ('revolt_chance_bonus', models.IntegerField(default=0)),
                ('defend_threshold_modifier', models.FloatField(default=0.0)),
                ('cavalry_scout_bonus', models.IntegerField(default=0)),
                ('morale_roll_bonus', models.IntegerField(default=0)),
                ('loot_found_modifier', models.FloatField(default=0.0)),
                ('forage_modifier', models.FloatField(default=0.0)),
                ('siege_engine_build_modifier', models.FloatField(default=0.0)),
                ('morale_loss_battle_modifier', models.FloatField(default=0.0)),
                ('recruitement_rate_good_country_bonus', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RefMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase)),
                ('discord_url', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=True)),
                ('completed_by', models.TextField(blank=True, default='ref')),
            ],
        ),
        migrations.AddField(
            model_name='detachment',
            name='siege_tower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_hex', to='cataphract.detachment'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_army', to='cataphract.army'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='description',
            field=models.TextField(default='unit', help_text='A little description of the unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unittype',
            name='harrier_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commander',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='bio',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(default=faker.providers.company.Provider.company, max_length=200),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='strongholds',
            name='name',
            field=models.CharField(default=faker.providers.address.Provider.city, max_length=200),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='world',
            name='world_name',
            field=models.CharField(default=faker.providers.person.Provider.last_name),
        ),
        migrations.CreateModel(
            name='playerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(help_text='Message content')),
                ('sent', models.DateTimeField(verbose_name='start of order')),
                ('recieved', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=True)),
                ('recieving_commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recieving_commander', to='cataphract.commander')),
                ('sending_commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sending_commander', to='cataphract.commander')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('modifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cataphract.modifier')),
                ('name', models.CharField(default=faker.providers.person.Provider.first_name, max_length=200)),
                ('desc', models.TextField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.commander')),
            ],
            bases=('cataphract.modifier',),
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('modifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cataphract.modifier')),
                ('name', models.CharField(default=faker.providers.person.Provider.first_name, max_length=200)),
                ('desc', models.TextField()),
                ('owners', models.ManyToManyField(to='cataphract.commander')),
            ],
            bases=('cataphract.modifier',),
        ),
    ]
