# Generated by Django 5.2 on 2026-01-19 17:58

import django.db.models.deletion
import faker.providers.address
import faker.providers.company
import faker.providers.lorem
import faker.providers.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0014_world_army_harried_commander_map_sprite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase)),
                ('discord_url', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=True)),
                ('completed_by', models.TextField(blank=True, default='ref')),
            ],
        ),
        migrations.RemoveField(
            model_name='world',
            name='world_height',
        ),
        migrations.RemoveField(
            model_name='world',
            name='world_width',
        ),
        migrations.AddField(
            model_name='detachment',
            name='siege_tower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_hex', to='cataphract.detachment'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_army', to='cataphract.army'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='description',
            field=models.TextField(default='', help_text='A little description of the unit'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='harrier_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commander',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='bio',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(default=faker.providers.company.Provider.company, max_length=200),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=faker.providers.lorem.Provider.word, max_length=200),
        ),
        migrations.AlterField(
            model_name='strongholds',
            name='name',
            field=models.CharField(default=faker.providers.address.Provider.city, max_length=200),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='world',
            name='world_name',
            field=models.CharField(default=faker.providers.person.Provider.last_name),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=faker.providers.address.Provider.country, max_length=200)),
                ('bio', models.TextField()),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cataphract.world')),
            ],
        ),
        migrations.AddField(
            model_name='hex',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.map'),
        ),
        migrations.AddField(
            model_name='region',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cataphract.map'),
        ),
        migrations.CreateModel(
            name='playerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(help_text='Message content')),
                ('sent', models.DateTimeField(verbose_name='start of order')),
                ('recieved', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=True)),
                ('recieving_commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recieving_commander', to='cataphract.commander')),
                ('sending_commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sending_commander', to='cataphract.commander')),
            ],
        ),
    ]
