# Generated by Django 5.2 on 2026-01-19 17:39

import faker.providers.address
import faker.providers.company
import faker.providers.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0015_modifier_refmessage_detachment_siege_tower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='map_sprite',
            field=models.ImageField(blank=True, null=True, upload_to='units/'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='commander',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='portraits/'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='bio',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(default=faker.providers.company.Provider.company, max_length=200),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='refmessage',
            name='message',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='strongholds',
            name='name',
            field=models.CharField(default=faker.providers.address.Provider.city, max_length=200),
        ),
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='world',
            name='world_name',
            field=models.CharField(default=faker.providers.person.Provider.last_name),
        ),
    ]
