# Generated by Django 5.2 on 2026-01-26 17:35

import django.db.models.deletion
import django.utils.timezone
import faker.providers.address
import faker.providers.company
import faker.providers.lorem
import faker.providers.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0015_refmessage_remove_world_world_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='commander',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='bio',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(default=faker.providers.company.Provider.company, max_length=200),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='hex',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hexes', to='cataphract.map'),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(default=faker.providers.address.Provider.country, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='refmessage',
            name='message',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='region',
            name='last_recruitement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last recruitment'),
        ),
        migrations.AlterField(
            model_name='region',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='cataphract.map'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=faker.providers.lorem.Provider.word, max_length=200),
        ),
        migrations.AlterField(
            model_name='strongholds',
            name='name',
            field=models.CharField(default=faker.providers.address.Provider.city, max_length=200),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='world',
            name='last_tick',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last ingame tick'),
        ),
        migrations.AlterField(
            model_name='world',
            name='world_name',
            field=models.CharField(default=faker.providers.person.Provider.last_name),
        ),
    ]
