# Generated by Django 5.2 on 2026-02-12 21:40

import faker.providers.address
import faker.providers.company
import faker.providers.lorem
import faker.providers.person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataphract', '0016_map_image_alter_commander_name_alter_detachment_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hex',
            name='tile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commander',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='bio',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(default=faker.providers.company.Provider.company, max_length=200),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(default=faker.providers.address.Provider.country, max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.name, max_length=200),
        ),
        migrations.AlterField(
            model_name='refmessage',
            name='message',
            field=models.TextField(blank=True, default=faker.providers.company.Provider.catch_phrase),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=faker.providers.lorem.Provider.word, max_length=200),
        ),
        migrations.AlterField(
            model_name='strongholds',
            name='name',
            field=models.CharField(default=faker.providers.address.Provider.city, max_length=200),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(default=faker.providers.person.Provider.first_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='world',
            name='world_name',
            field=models.CharField(default=faker.providers.person.Provider.last_name),
        ),
    ]
